Repository uasoft-indonesia/badaso-post-module, pull requests merged in 2021-06, with the labels that each got.

#40 Apply fixes from StyleCI
  src/Helpers/GetData.php
Labels: backend

#39 analytics fallback
  src/Helpers/GetData.php
  src/resources/js/pages/posts/browse.vue
Labels: backend, bugfix, frontend

#41 Bugfix/no analytics
  src/resources/js/pages/posts/browse.vue
Labels: backend, bugfix, frontend

#42 Merge develop to main
  README.md
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Helpers/GetData.php
  src/Providers/BadasoBlogModuleServiceProvider.php
  src/resources/js/pages/posts/browse.vue
  src/resources/lang/en/validation.php
  src/resources/lang/id/validation.php
Labels: backend, frontend

#50 Apply fixes from StyleCI
  src/Controllers/PostController.php
Labels: backend

#49 bugfix on blog module
  README.md
  src/Commands/BadasoBlogSeed.php
  src/Controllers/PostController.php
  src/Providers/BadasoBlogModuleServiceProvider.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BlogFixedMenuItemSeeder.php
  src/Seeder/BlogMenusSeeder.php
  src/Seeder/BlogPermissionsSeeder.php
  src/Seeder/BlogRolePermissionsSeeder.php
  src/Seeder/BlogRolesSeeder.php
Labels: backend, bugfix

#51 Merge develop to main
  README.md
  src/Commands/BadasoBlogSeed.php
  src/Controllers/PostController.php
  src/Providers/BadasoBlogModuleServiceProvider.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BlogFixedMenuItemSeeder.php
  src/Seeder/BlogMenusSeeder.php
  src/Seeder/BlogPermissionsSeeder.php
  src/Seeder/BlogRolePermissionsSeeder.php
  src/Seeder/BlogRolesSeeder.php
Labels: backend

#53 Apply fixes from StyleCI
  src/Controllers/PostController.php
Labels: backend

#52 implement management file
  src/Controllers/PostController.php
Labels: backend, bugfix

#54 Merge develop to main
  src/Controllers/PostController.php
Labels: backend

#55 Enhancement/upgrade laravel 8
  src/Commands/BadasoBlogSetup.php
  src/Controllers/PostController.php
  src/Providers/BadasoBlogModuleServiceProvider.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BlogFixedMenuItemSeeder.php
  src/Seeder/BlogMenusSeeder.php
  src/Seeder/BlogPermissionsSeeder.php
  src/Seeder/BlogRolePermissionsSeeder.php
  src/Seeder/BlogRolesSeeder.php
  src/resources/js/router/routes.js
Labels: backend, enhancement, frontend

#57 Merge develop to main
  src/Commands/BadasoBlogSetup.php
  src/Controllers/PostController.php
  src/Providers/BadasoBlogModuleServiceProvider.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BlogFixedMenuItemSeeder.php
  src/Seeder/BlogMenusSeeder.php
  src/Seeder/BlogPermissionsSeeder.php
  src/Seeder/BlogRolePermissionsSeeder.php
  src/Seeder/BlogRolesSeeder.php
  src/resources/js/router/routes.js
Labels: backend, frontend

#59 Apply fixes from StyleCI
  src/Commands/BadasoBlogSetup.php
  src/Controllers/PostController.php
  src/Seeder/BlogRolePermissionsSeeder.php
Labels: backend

#60 Merge develop to main
  composer.json
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BlogFixedMenuItemSeeder.php
  src/Seeder/BlogMenusSeeder.php
  src/Seeder/BlogPermissionsSeeder.php
  src/Seeder/BlogRolePermissionsSeeder.php
  src/Seeder/BlogRolesSeeder.php
Labels: backend, dependencies

#62 Apply fixes from StyleCI
  src/Controllers/PostController.php
Labels: backend

#63 change url on upload content img
  src/resources/js/pages/posts/read.vue
Labels: bugfix, frontend

#64 Merge develop to main
  src/resources/js/pages/posts/read.vue
Labels: frontend

#67 Apply fixes from StyleCI
  src/Exceptions/InvalidPeriod.php
  src/Helpers/GetData.php
Labels: backend

#69 Apply fixes from StyleCI
  src/Helpers/GetData.php
Labels: backend

#71 Apply fixes from StyleCI
  src/Exceptions/InvalidPeriod.php
Labels: backend

#68 Bugfix/v2/add period
  src/Exceptions/InvalidPeriod.php
  src/Helpers/GetData.php
  src/Helpers/Period.php
Labels: backend, bugfix

#70 Add period helper
  src/Exceptions/InvalidPeriod.php
  src/Helpers/GetData.php
  src/Helpers/Period.php
Labels: backend, bugfix

#72 Merge develop to main
  src/Exceptions/InvalidPeriod.php
  src/Helpers/GetData.php
  src/Helpers/Period.php
Labels: backend

#75 Apply fixes from StyleCI
  src/Controllers/PostController.php
Labels: backend

#76 Apply fixes from StyleCI
  src/Controllers/PostController.php
Labels: backend

#79 Apply fixes from StyleCI
  src/Commands/BadasoBlogSetup.php
Labels: backend

#80 hide tables when setup
  src/Commands/BadasoBlogSetup.php
Labels: backend, bugfix

#78 hide tables when setup
  src/Commands/BadasoBlogSetup.php
Labels: backend

#77 add next & previous post
  src/Controllers/PostController.php
Labels: backend, feature

#74 add next & previous post
  src/Controllers/PostController.php
Labels: backend, feature

#81 Merge develop to main
  src/Commands/BadasoBlogSetup.php
  src/Controllers/PostController.php
Labels: backend

#82 Add media base url meta
  src/resources/js/pages/posts/edit.vue
  src/resources/js/pages/posts/read.vue
Labels: feature, frontend

#83 Add media base url meta
  src/resources/js/pages/posts/edit.vue
  src/resources/js/pages/posts/read.vue
Labels: feature, frontend

#85 Bump 2.0.0-rc.4
  composer.json
Labels: dependencies
