Repository uasoft-indonesia/badaso-post-module, pull requests merged in 2021-10, with the labels that each got.

#112 Apply fixes from StyleCI
  src/Controllers/PostController.php
  src/Seeder/PostFixedMenuItemSeeder.php
  src/Seeder/PostMenusSeeder.php
  src/Seeder/PostRolePermissionsSeeder.php
  src/Seeder/PostRolesSeeder.php
Labels: backend

#111 Add author api
  src/Controllers/PostController.php
  src/Routes/api.php
  src/Seeder/PostFixedMenuItemSeeder.php
  src/Seeder/PostMenusSeeder.php
  src/Seeder/PostRolePermissionsSeeder.php
  src/Seeder/PostRolesSeeder.php
Labels: backend, feature

#113 Rebase develop
  src/Controllers/PostController.php
  src/Routes/api.php
  src/Seeder/PostFixedMenuItemSeeder.php
  src/Seeder/PostMenusSeeder.php
  src/Seeder/PostRolePermissionsSeeder.php
  src/Seeder/PostRolesSeeder.php
Labels: backend

#115 Bump to 2.0.0
  composer.json
Labels: dependencies
