Repository uasoft-indonesia/badaso-post-module, pull requests merged in 2021-05, with the labels that each got.

#10 add improvement to analytics
  src/Commands/BadasoBlogSetup.php
  src/Helpers/GetData.php
  src/resources/js/pages/posts/browse.vue
Labels: backend, frontend

#15 Apply fixes from StyleCI
  src/Controllers/Api/PostController.php
Labels: backend

#16 Apply fixes from StyleCI
  src/Commands/BadasoBlogSetup.php
  src/Controllers/Api/PostController.php
Labels: backend

#14 add thumbnail on fetch
  src/Commands/BadasoBlogSetup.php
  src/Controllers/Api/PostController.php
Labels: backend

#17 Merge develop to main
  README.md
  composer.json
  src/Commands/BadasoBlogSetup.php
  src/Config/badaso-blog.php
  src/Controllers/Api/PostController.php
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Helpers/GetData.php
  src/Models/Post.php
  src/Routes/api.php
  src/Swagger/comment.php
  src/Swagger/post.php
  src/resources/js/api/modules/readme.md
  src/resources/js/components/index.js
  src/resources/js/components/readme.md
  src/resources/js/lang/modules/readme.md
  src/resources/js/pages/posts/browse.vue
  src/resources/js/pages/readme.md
  src/resources/js/router/excludeRouter.js
  src/resources/js/router/readme.md
  src/resources/js/store/readme.md
  src/resources/js/utils/readme.md
Labels: backend, dependencies, frontend

#20 Apply fixes from StyleCI
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Helpers/GetData.php
  src/Migrations/2021_05_21_035240_add_thumbnail_to_posts_table.php
  src/Migrations/2021_05_21_035351_alter_foreign_key_on_comments_table.php
Labels: backend

#19 Feature/thumbnail
  composer.json
  src/Controllers/Api/PostController.php
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Helpers/GetData.php
  src/Migrations/2021_05_21_035240_add_thumbnail_to_posts_table.php
  src/Migrations/2021_05_21_035351_alter_foreign_key_on_comments_table.php
  src/Models/Post.php
  src/Routes/api.php
  src/Swagger/post.php
  src/resources/js/api/modules/badaso-blog.js
  src/resources/js/api/modules/badaso-category.js
  src/resources/js/api/modules/badaso-comment.js
  src/resources/js/api/modules/badaso-post.js
  src/resources/js/api/modules/badaso-tags.js
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/posts/add.vue
  src/resources/js/pages/posts/edit.vue
  src/resources/js/pages/posts/read.vue
  src/resources/js/router/routes.js
Labels: backend, dependencies, frontend

#21 Merge develop to main
  README.md
  composer.json
  src/Controllers/Api/PostController.php
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Helpers/GetData.php
  src/Migrations/2021_05_21_035240_add_thumbnail_to_posts_table.php
  src/Migrations/2021_05_21_035351_alter_foreign_key_on_comments_table.php
  src/Models/Post.php
  src/Routes/api.php
  src/Swagger/post.php
  src/resources/js/api/modules/badaso-blog.js
  src/resources/js/api/modules/badaso-category.js
  src/resources/js/api/modules/badaso-comment.js
  src/resources/js/api/modules/badaso-post.js
  src/resources/js/api/modules/badaso-tags.js
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/posts/add.vue
  src/resources/js/pages/posts/edit.vue
  src/resources/js/pages/posts/read.vue
  src/resources/js/router/routes.js
Labels: backend, dependencies, frontend

#23 Apply fixes from StyleCI
  src/Commands/BadasoBlogSetup.php
Labels: backend

#22 change location seeder publish and rename config
  .github/autolabeler.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  src/Commands/BadasoBlogSetup.php
  src/Providers/BadasoBlogModuleServiceProvider.php
Labels: backend, config

#24 Fix composer versioning
  composer.json
Labels: bugfix, dependencies

#26 bump version to 1.0.0-alpha.3
  composer.json
Labels: dependencies

#27 Change default prefix
  src/resources/js/router/routes.js
Labels: bugfix, frontend

#31 Apply fixes from StyleCI
  src/Commands/BadasoBlogSeed.php
  src/Providers/BadasoBlogModuleServiceProvider.php
Labels: backend

#30 Add new command, change readme, move the seeders
  README.md
  src/Commands/BadasoBlogSeed.php
  src/Providers/BadasoBlogModuleServiceProvider.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BlogFixedMenuItemSeeder.php
  src/Seeder/BlogMenusSeeder.php
  src/Seeder/BlogPermissionsSeeder.php
  src/Seeder/BlogRolePermissionsSeeder.php
  src/Seeder/BlogRolesSeeder.php
Labels: backend, bugfix

#32 Merge develop to main
  README.md
  src/Commands/BadasoBlogSeed.php
  src/Providers/BadasoBlogModuleServiceProvider.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BlogFixedMenuItemSeeder.php
  src/Seeder/BlogMenusSeeder.php
  src/Seeder/BlogPermissionsSeeder.php
  src/Seeder/BlogRolePermissionsSeeder.php
  src/Seeder/BlogRolesSeeder.php
  src/resources/js/router/routes.js
Labels: backend, frontend

#36 Change category & tags to optional
  src/Controllers/PostController.php
Labels: backend, bugfix

#35 Update readme.md
  README.md
Labels: bugfix

#38 Apply fixes from StyleCI
  src/Helpers/GetData.php
  src/resources/lang/en/validation.php
  src/resources/lang/id/validation.php
Labels: backend

#37 Bugfix/ignore analytics
  README.md
  src/Controllers/CommentController.php
  src/Helpers/GetData.php
  src/Providers/BadasoBlogModuleServiceProvider.php
  src/resources/lang/en/validation.php
  src/resources/lang/id/validation.php
Labels: backend, bugfix
