Repository uasoft-indonesia/badaso-post-module, pull requests merged in 2021-07, with the labels that each got.

#86 Update composer.json
  composer.json
Labels: dependencies

#87 Rename blog to post
  README.md
  composer.json
Labels: dependencies

#91 Rename blog to post
  src/BadasoPostModule.php
  src/Commands/BadasoPostSetup.php
  src/Config/badaso-blog.php
  src/Config/badaso-post.php
  src/Controllers/CategoryController.php
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Controllers/TagController.php
  src/Exceptions/InvalidPeriod.php
  src/Facades/BadasoPostModule.php
  src/Helpers/GetData.php
  src/Helpers/Period.php
  src/Models/Category.php
  src/Models/Comment.php
  src/Models/Post.php
  src/Models/Tag.php
  src/Providers/BadasoPostModuleServiceProvider.php
  src/Routes/api.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BadasoPostModuleSeed.php
  src/Seeder/PostFixedMenuItemSeeder.php
  src/Seeder/PostMenusSeeder.php
  src/Seeder/PostPermissionsSeeder.php
  src/Seeder/PostRolePermissionsSeeder.php
  src/Seeder/PostRolesSeeder.php
  src/Swagger/category.php
  src/Swagger/comment.php
  src/Swagger/post.php
  src/Swagger/tag.php
  src/resources/js/api/modules/badaso-blog.js
  src/resources/js/api/modules/badaso-category.js
  src/resources/js/api/modules/badaso-comment.js
  src/resources/js/api/modules/badaso-post.js
  src/resources/js/api/modules/badaso-tags.js
  src/resources/js/pages/index.vue
  src/resources/js/utils/readme.md
Labels: backend, enhancement, frontend

#90 Rename blog to post
  src/BadasoPostModule.php
  src/Commands/BadasoPostSetup.php
  src/Config/badaso-blog.php
  src/Config/badaso-post.php
  src/Controllers/CategoryController.php
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Controllers/TagController.php
  src/Exceptions/InvalidPeriod.php
  src/Facades/BadasoPostModule.php
  src/Helpers/GetData.php
  src/Helpers/Period.php
  src/Models/Category.php
  src/Models/Comment.php
  src/Models/Post.php
  src/Models/Tag.php
  src/Providers/BadasoPostModuleServiceProvider.php
  src/Routes/api.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BadasoPostModuleSeed.php
  src/Seeder/PostFixedMenuItemSeeder.php
  src/Seeder/PostMenusSeeder.php
  src/Seeder/PostPermissionsSeeder.php
  src/Seeder/PostRolePermissionsSeeder.php
  src/Seeder/PostRolesSeeder.php
  src/Swagger/category.php
  src/Swagger/comment.php
  src/Swagger/post.php
  src/Swagger/tag.php
  src/resources/js/api/modules/badaso-blog.js
  src/resources/js/api/modules/badaso-category.js
  src/resources/js/api/modules/badaso-comment.js
  src/resources/js/api/modules/badaso-post.js
  src/resources/js/api/modules/badaso-tags.js
  src/resources/js/pages/index.vue
  src/resources/js/utils/readme.md
Labels: backend, enhancement, frontend

#92 Prepare for v2.0.0-rc.5
  composer.json
  src/BadasoPostModule.php
  src/Commands/BadasoPostSetup.php
  src/Config/badaso-blog.php
  src/Config/badaso-post.php
  src/Controllers/CategoryController.php
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Controllers/TagController.php
  src/Exceptions/InvalidPeriod.php
  src/Facades/BadasoPostModule.php
  src/Helpers/GetData.php
  src/Helpers/Period.php
  src/Models/Category.php
  src/Models/Comment.php
  src/Models/Post.php
  src/Models/Tag.php
  src/Providers/BadasoPostModuleServiceProvider.php
  src/Routes/api.php
  src/Seeder/BadasoModuleBlogSeeder.php
  src/Seeder/BadasoPostModuleSeed.php
  src/Seeder/PostFixedMenuItemSeeder.php
  src/Seeder/PostMenusSeeder.php
  src/Seeder/PostPermissionsSeeder.php
  src/Seeder/PostRolePermissionsSeeder.php
  src/Seeder/PostRolesSeeder.php
  src/Swagger/category.php
  src/Swagger/comment.php
  src/Swagger/post.php
  src/Swagger/tag.php
  src/resources/js/api/modules/badaso-blog.js
  src/resources/js/api/modules/badaso-category.js
  src/resources/js/api/modules/badaso-comment.js
  src/resources/js/api/modules/badaso-post.js
  src/resources/js/api/modules/badaso-tags.js
  src/resources/js/pages/index.vue
  src/resources/js/utils/readme.md
Labels: backend, dependencies, frontend

#95 Apply fixes from StyleCI
  src/Models/Comment.php
  src/Models/PostTag.php
  src/Swagger/comment.php
  src/Swagger/post.php
Labels: backend

#97 Bump to 2.0.0-rc.6
  composer.json
Labels: dependencies

#99 Fix migration still using uuid
  src/Controllers/CategoryController.php
  src/Controllers/CommentController.php
  src/Controllers/PostController.php
  src/Controllers/TagController.php
  src/Migrations/2021_04_28_090801_create_categories_table.php
  src/Migrations/2021_04_28_090805_create_post_tag_table.php
Labels: backend, bugfix

#101 Apply fixes from StyleCI
  src/Controllers/PostController.php
Labels: backend

#100 Fix post on detail
  src/Controllers/PostController.php
Labels: backend, bugfix

#102 Fix post on detail
  src/Controllers/PostController.php
Labels: backend, bugfix
