Repository uasoft-indonesia/badaso-post-module, pull requests merged in 2021-08, with the labels that each got.

#103 Prepare Next Release
  composer.json
  src/Controllers/PostController.php
Labels: backend, dependencies

#104 Remove old concept of file manager
  src/resources/js/pages/category/read.vue
  src/resources/js/pages/comment/read.vue
  src/resources/js/pages/posts/read.vue
  src/resources/js/pages/tags/read.vue
Labels: enhancement, frontend

#105 Remove old concept of file manager
  src/resources/js/pages/category/read.vue
  src/resources/js/pages/comment/read.vue
  src/resources/js/pages/posts/read.vue
  src/resources/js/pages/tags/read.vue
Labels: enhancement, frontend

#106 Prepare 2.0.0-rc.8
  composer.json
  src/resources/js/pages/category/read.vue
  src/resources/js/pages/comment/read.vue
  src/resources/js/pages/posts/read.vue
  src/resources/js/pages/tags/read.vue
Labels: frontend, dependencies

#107 Rename badaso-blog to badaso-post-public
  src/Controllers/PostController.php
  src/resources/js/api/modules/badaso-post-public.js
Labels: enhancement, frontend, backend

#108 Rename blog to post public
  src/resources/js/api/modules/badaso-post-public.js
Labels: enhancement, frontend

#109 Prepare next release
  composer.json
  src/resources/js/api/modules/badaso-post-public.js
Labels: frontend, dependencies
